
id: asdf://astropy.org/astropy/manifests/units-1.0.0
extension_uri: asdf://astropy.org/astropy/extensions/units-1.0.0
title: Astropy unit extension 1.0.0
description: |-
  A set of tags to inject into asdf-standard to enable serializing astropy units
  related objects
tags:
  - tag_uri: tag:astropy.org:astropy/units/unit-1.0.0
    schema_uri: http://stsci.edu/schemas/asdf/unit/unit-1.0.0
    title: Represents an astropy derived unit
    description: |-
      Supports serialization of the non-VOunits supported by astropy
