[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            #"extension-helpers",
            "oldest-supported-numpy",
            #"cython==0.29.14"
	    ]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 120
force-exclude = '''
^/(
  (
      \.eggs
    | \.git
    | \.pytest_cache
    | \.tox
    | scripts
    | build
    | dist
  )/
)
'''
