name: Release

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 6am UTC
    - cron: '0 6 * * 1'
  push:
    branches:
      - main
      - '*.x'
    tags:
      - "*"
  pull_request:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  test_wheel_building:
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    if: (github.event_name == 'push' || github.event_name == 'pull_request')
    with:
      upload_to_pypi: false
      upload_to_anaconda: false
      test_extras: test
      test_command: pytest --pyargs asdf_astropy

  build-n-publish:
    permissions:
      contents: none
    if: (github.event_name == 'release')
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      test_extras: test
      test_command: pytest --pyargs test_package
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD }}
