name: Release

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 6am UTC
    - cron: '0 6 * * 1'
  push:
    branches:
      - main
      - '*.x'
    tags:
      - "*"
  pull_request:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  test_wheel_building:
    permissions:
      contents: none
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    if: (github.event_name == 'push' || github.event_name == 'pull_request')
    with:
      upload_to_pypi: false
      upload_to_anaconda: false
      test_extras: test
      test_command: pytest --pyargs asdf_astropy

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    if: ((github.event_name == 'release') || contains(github.event.pull_request.labels.*.name, 'Build wheels'))

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install python-build and twine
      run: python -m pip install build "twine>=3.3"

    - name: Build package
      run: python -m build --sdist --wheel .

    - name: List result
      run: ls -l dist

    - name: Check long_description
      run: python -m twine check --strict dist/*

    - name: Test package
      run: |
        cd ..
        python -m venv testenv
        testenv/bin/pip install pytest pytest-astropy scipy asdf-astropy/dist/*.whl
        testenv/bin/pytest asdf-astropy
    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}
